# Generated by Django 5.2.15 on 2026-06-24 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_club_clubphoto_delete_clube'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='nome',
            new_name='name',
        ),
    ]
